export default {

  PROFILE_CREATED: 'PROFILE_CREATED',
  USER_LOGGED_IN: 'USER_LOGGED_IN',
  FETCH_ALL_BIKES: 'FETCH_ALL_BIKES',
  TOP_SELECTED: 'TOP_SELECTED',
  FETCH_FRONT_PAGE: 'FETCH_FRONT_PAGE',
  SEND_CONTACT_EMAIL: 'SEND_CONTACT_EMAIL',
  DELETE_FEED: 'DELETE_FEED'


}
